services:
  app:
    image: localhost/decidim-sweden:0.29.3
    command: bundle exec passenger start
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - app-storage:/code/storage
    environment:
      - RAILS_ENV=production
      - "DATABASE_URL=postgres://decidim:$DATABASE_PASSWORD@pg:5432/decidim"
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD="$DATABASE_PASSWORD"
      - DECIDIM_FORCE_SSL=true
      - DOMAIN=decidim.localdomain
      - GEOCODER_LOOKUP_API_KEY="$HERE_API_KEY"
      - RAILS_LOG_TO_STDOUT=1
      - "REDIS_URL=redis://redis:6379/1"
      - SECRET_KEY_BASE="$SECRET_KEY_BASE"
    depends_on:
      - pg
  app-worker:
    image: localhost/decidim-sweden:0.29.3
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=production
      - "DATABASE_URL=postgres://decidim:$DATABASE_PASSWORD@pg:5432/decidim"
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD="$DATABASE_PASSWORD"
      - DECIDIM_FORCE_SSL=true
      - DOMAIN=decidim.localdomain
      - RAILS_LOG_TO_STDOUT=1
      - "REDIS_URL=redis://redis:6379/1"
      - SECRET_KEY_BASE="$SECRET_KEY_BASE"
    depends_on:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="$DATABASE_PASSWORD"
  redis:
    image: "redis:latest"
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
  app-storage: {}
